In [3]:
import numpy as np

In [ ]:
#1

In [6]:
a = np.array([[1, 6],
            [2, 8],
            [3, 11],
            [3, 10],
            [1, 7]])


In [10]:
print(a.mean())

5.2


In [11]:
print(a.mean(axis=0))

[2.  8.4]


In [17]:
print(a.mean(axis=1))

[3.5 5.  7.  6.5 4. ]


In [18]:
mean_a = a.mean(axis=0)

In [27]:
#2

In [20]:
print(mean_a[0])

2.0


In [24]:
a_centered = a - mean_a

In [25]:
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [26]:
#3

In [40]:
a[:,0]

array([1, 2, 3, 3, 1])

In [41]:
a.shape

(5, 2)

In [43]:
a[:,1]

array([ 6,  8, 11, 10,  7])

In [50]:
a_centered_sp = a[:,0].dot(a[:,1])
a_centered_sp

92

In [47]:
a_centered_sp/len(a-1)

18.4

In [ ]:
#4

In [51]:
a.transpose()

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [54]:
cov_a = np.cov(a.transpose())

In [55]:
cov_a

array([[1. , 2. ],
       [2. , 4.3]])

In [56]:
cov_a[1,0]

2.0